#! /bin/sh

case "$1" in
	start)
		/usr/bin/module_load hello
		/usr/bin/scull_load
		/usr/bin/aesdchar_load
		;;
	stop)
		/usr/bin/module_unload hello
		/usr/bin/scull_unload
		/usr/bin/aesdchar_load
		;;
	*)
		echo "Usage: $0 {start|stop} xxxx"
		exit 1
esac
exit 0
